<?php

class AbstractController
{
    private \Twig\Environment $twig;
    public function __construct()
    {
        $loader = new \Twig\Loader\FilesystemLoader('templates');
        $twig = new \Twig\Environment($loader,[
            'debug' => true,
        ]);

        $twig->addExtension(new \Twig\Extension\DebugExtension());

        $this->twig = $twig;
    }

    protected function render(string $template, array $data) : void
    {
        //Generated by GitHub Copilot : peux tu faire en sorte que quand l'utilisateur n'est pas connecté cela affiche Connection et inscription et que quand il est connecté cela affiche Deconnection
        $data['user'] = isset($_SESSION['email']) ? [
            'email' => $_SESSION['email'],
            'firstName' => $_SESSION['firstName'] ?? null,
            'lastName' => $_SESSION['lastName'] ?? null,
        ] : null;
        
        echo $this->twig->render($template, $data);
    }

    protected function redirect(string $url) : void
    {
        header('Location: '.$url);
        exit;
    }
}
